# Generated by Django 2.2.1 on 2019-05-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_date'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
